name: Build

on:
  push:
    branches: [ main, master, feature/* ]
  pull_request:
    branches: [ main, master ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y cmake g++ libsqlite3-dev
    
    - name: Configure CMake
      run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=Release -DBUILD_TESTS=OFF -DCODE_COVERAGE=OFF
      
    - name: Build
      run: cmake --build ${{github.workspace}}/build --config Release
      
    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: music-store-app
        path: ${{github.workspace}}/build/music_store_app